---
  - name: Push the container image on local execution
    changed_when: true
    command:
      cmd: "node deploy/docker_push.js"
      chdir: "../.."
    environment:
      DOCKER_REGISTRY_PATH: "{{ DOCKER_REGISTRY_PATH }}"
